language: elixir

elixir:
  - 1.8.0

otp_release:
  - 21.2

sudo: required

services:
  - docker

before_script:
  - docker pull eventstore/eventstore
  - docker run -it -p 2113:2113 -p 1113:1113 -e EVENTSTORE_START_STANDARD_PROJECTIONS=True -e EVENTSTORE_RUN_PROJECTIONS=all eventstore/eventstore
