language: elixir

elixir:
  - 1.8.0

otp_release:
  - 21.2

sudo: required

services:
  - docker

before_install:
  - docker pull eventstore/eventstore

before_script:
  - socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock &
